# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 19:19
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


def forwards_func(apps, schema_editor):
	db_alias = schema_editor.connection.alias
	UserEntryStatus = apps.get_model('feeds', 'UserEntryStatus')
	for status in UserEntryStatus.objects.using(db_alias).all():
		status.is_read = not status.is_unread
		status.save()
	UserEntryStatus.objects.using(db_alias).filter(is_read=True).update(
		read_time=timezone.now()
	)

def reverse_func(apps, schema_editor): #pylint: disable=unused-argument
	pass


class Migration(migrations.Migration):

	dependencies = [
		('feeds', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='userentrystatus',
			name='is_read',
			field=models.BooleanField(db_index=True, default=False, verbose_name='news is readed'),
		),
		migrations.AddField(
			model_name='userentrystatus',
			name='read_time',
			field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last read time'),
		),
		migrations.RunPython(forwards_func, reverse_func),
		migrations.RemoveField(
			model_name='userentrystatus',
			name='is_unread',
		),
	]
