# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 19:19
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone


def forwards_func(apps, schema_editor):
	db_alias = schema_editor.connection.alias
	UserEntryStatus = apps.get_model('feeds', 'UserEntryStatus')
	for status in UserEntryStatus.objects.using(db_alias).all():
		status.is_read = not status.is_unread
		status.save()
	UserEntryStatus.objects.using(db_alias).filter(is_read=True).update(
		read_time=timezone.now()
	)

def reverse_func(apps, schema_editor): #pylint: disable=unused-argument
	pass


class Migration(migrations.Migration):

	dependencies = [
		('feeds', '0002_auto_20161022_1919'),
	]

	operations = [
		migrations.RunPython(forwards_func, reverse_func),
	]
