# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('feeds', '0003_auto_20161022_1919'),
	]

	operations = [
		migrations.RemoveField(
			model_name='userentrystatus',
			name='is_unread',
		),
	]
