# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('feeds', '0004_auto_20161022_1919'),
	]

	operations = [
		migrations.AddField(
			model_name='userentrystatus',
			name='created',
			field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created date'),
		),
		migrations.AlterIndexTogether(
			name='userentrystatus',
			index_together=set([('user', 'created', 'read_time', 'is_read')]),
		),
	]
