# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models, connection


def forwards_func(apps, schema_editor): # pylint: disable=unused-argument
	cursor = connection.cursor()
	cursor.execute('UPDATE feeds_userentrystatus SET created = (SELECT created FROM feeds_entry WHERE feeds_userentrystatus.entry_id = feeds_entry.id)')


def reverse_func(apps, schema_editor): #pylint: disable=unused-argument
	pass


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('feeds', '0005_auto_20170305_1628'),
	]

	operations = [
		migrations.RunPython(forwards_func, reverse_func),
		migrations.AlterField(
			model_name='userentrystatus',
			name='created',
			field=models.DateTimeField(db_index=True, verbose_name='created date'),
		),
		migrations.AlterIndexTogether(
			name='userentrystatus',
			index_together=set([('user', 'is_read', 'created')]),
		),
	]
