# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('feeds', '0006_auto_20170305_1651'),
	]

	operations = [
		migrations.AddField(
			model_name='entry',
			name='in_feed',
			field=models.BooleanField(default=True, verbose_name='this entry is included in feed'),
		),
	]
